In [1]:
print("Hello python")

Hello python


# Array Slicing

In [6]:
import numpy as np

arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)
l=len(arr)
print('length=',len(arr))
#slice 
#array_name[start : end,start included, end excluded]
print(arr[0:10])
print(arr[0:6])

[0 1 2 3 4 5 6 7 8 9]
length= 10
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]


In [10]:
#positive indices
print(arr[0:5])
print(arr[4:])
print(arr[:9])

[0 1 2 3 4]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]


In [18]:
#negative indices
print(arr[-1:])
print(arr[-3:-5])

[9]
[]


In [20]:
#step values in array slicing
print(arr[0:10:2])
#array_name[start : end:step size]
print(arr[0:10:3])
print(arr[0:10:5])

[0 2 4 6 8]
[0 3 6 9]
[0 5]


In [46]:
#slicing 2d array

arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)
print("\n")
print(arr1.size)
print("\n" ,arr1.ndim)
print("\n" ,arr1.shape)

#slicing
# arr[2_d array loc, range of elements]
print("\n")

print(arr1[0])

print("\n")

print(arr1[1])

print("\n")

print(arr1[0,1:4])

print("\n")

print(arr1[1,0:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


10

 2

 (2, 5)


[1 2 3 4 5]


[ 6  7  8  9 10]


[2 3 4]


[ 6  7  8  9 10]


In [53]:
print(arr1)
print('\n')
print(arr1[0:2,0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[[1 2]
 [6 7]]


In [54]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
15
(3, 5)


In [55]:
# 2, 3
# 20,30

print(arr[0:2,1:3])

# 20 30 40
# 22 33 44

print("\n",arr[1:3,1:4])

[[ 2  3]
 [20 30]]

 [[20 30 40]
 [22 33 44]]


In [8]:
import numpy as np
arr=np.array([1,3,5,6,2,8,7,9,4,0])
print(arr)
print(type(arr))
ar=np.sort(arr)
print(ar)

[1 3 5 6 2 8 7 9 4 0]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(ar)
index=[]
for i in ar:
    if i>3:
        index.append(True)
    else:
        index.append(False)
print(index)
newar=ar[index]
print(newar)

[0 1 2 3 4 5 6 7 8 9]
[False, False, False, False, True, True, True, True, True, True]
[4 5 6 7 8 9]
