In [20]:
import numpy as np

l=[1,2,3,4]
arr=np.array(l)
print(arr)
print(type(arr))
print("Dimension of array :",arr.ndim)
print("Access the elements in array")
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

[1 2 3 4]
<class 'numpy.ndarray'>
Dimension of array : 1
Access the elements in array
1
2
3
4


In [12]:
l1=[[20,50,60,80],[90,8,7,5]]
ar1=np.array(l1)
print(ar1)
print(type(ar1))
print("\nDimensions of ar1", ar1.ndim)
a=print("\nAccess first element in 2D array")
print(ar1[0])
print(type(a))
print("\nAccess first element in first dimension in 2D array ar1[0][0]")
print(ar1[0][0])
print("\nAnother method of accessing ar1[0,0]")
print(ar1[0,0])

[[20 50 60 80]
 [90  8  7  5]]
<class 'numpy.ndarray'>

Dimensions of ar1 2

Access first element in 2D array
[20 50 60 80]
<class 'NoneType'>

Access first element in first dimension in 2D array ar1[0][0]
20

Another method of accessing ar1[0,0]
20


In [33]:
L2=[[[100,200,300],[600,500,800],[900,685,300]]]
print(L2)
print(type(L2))
print('\n')
ar2=np.array(L2)
print('\n')
print(type(ar2))
print('\n')
print(ar2)
print("\n Dimension of ar2=",ar2.ndim)

print("\nAccess first element in first dimension in 3D array ar2[0][0]")
print(ar2[0][0])
print("\nAnother method of accessing ar2[0,0,0]")
print(ar2[0,0,0])
print('\n')
print(ar2[0,1,1])
print(ar2[0][0][2])
print(ar2[0][1][2])
print(ar2[0][1][0])

[[[100, 200, 300], [600, 500, 800], [900, 685, 300]]]
<class 'list'>




<class 'numpy.ndarray'>


[[[100 200 300]
  [600 500 800]
  [900 685 300]]]

 Dimension of ar2= 3

Access first element in first dimension in 3D array ar2[0][0]
[100 200 300]

Another method of accessing ar2[0,0,0]
100


500
300
800
600


In [30]:
arr = np.array([1, 2, 3, 4,5], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In [39]:
arr1=np.array([12,15,25,60],ndmin=1)
print(arr1)
print("Dimension of array arr1",arr1.ndim)
arr2=np.array(arr1,ndmin=5)
print(arr2)
print("Dimension of array arr2",arr2.ndim)

[12 15 25 60]
Dimension of array arr1 1
[[[[[12 15 25 60]]]]]
Dimension of array arr2 5
